

CREATE DATABASE hola_viajens;

USE hola_viajens;

CREATE TABLE usuario (
    id_usuario VARCHAR(13) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    nomeCompleto VARCHAR(40) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    email VARCHAR(40) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    lgin VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    senha VARCHAR(30) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    CONSTRAINT pkid_usuario PRIMARY KEY(id_usuario));

